### ISSUE TITLE
เพิ่มพ่อพันธุ์ 

### ISSUE THREAD

**Issue by ford19982541** [SEUP/CattleFarmer#14]
![image](https://user-images.githubusercontent.com/33016279/43301095-2e697e36-918d-11e8-99b5-3dc31316159b.png)

**Comment by ford19982541** [comment]
หากกดปุ่มยกเลิก จะไม่สามารถรีเซ็ตข้อมูลได้ (ที่เป็น component )

**Comment by pchaow** [comment]
ไปเขียน reset ตอน mounted ข้อมูลจิ
