### ISSUE TITLE
[CattleAdmin] เเก้ปัญหาเเอดมินหลุดอออกจากระบบ โดยไม่ทราบสามาเหตุ

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleFarmer#19]

**Comment by pchaow** [comment]
สาเหตุการจากการ login ทั้งส่วนของ farmer / admin ซึ่งใช้ Local storage อันเดียวกันมันจึงทับไลน์กัน
8c4520c73e59217951c4b5f3f810d5fbe5c8469c
