### ISSUE TITLE
[cattle farmer] เพิ่มโค อยากบังคับให้ใส่เบอร์หู หรือ ชื่อ โคอย่างใดอย่างหนึ่ง ไม่ใช่บังบังชื่อโคอย่างเดียว

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleFarmer#43]
คือลูกค้าบอกว่า เวลาฟาร์มใหญ่ๆ จะมีเเค่เบอร์หูอ่ะครับ
ส่วน ฟาร์มเล็กๆ ก็จะมีชื่อ อย่างเดียว

**Comment by pchaow** [comment]
https://indicative.adonisjs.com/docs/requiredwithoutany
