### ISSUE TITLE
[cattle farmer]อยากให้มีเเจ้งเตือนเกี่ยวกับ การผสมพันธุ์ 

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleFarmer#46]
ก็น่าจะเป็น เเนวๆ ปฏิทินที่มี event นะครับ หรือจะเป็นเเนวอื่นๆดีครับ

**Comment by pchaow** [comment]
รอปรับปรุงการผสมพันธุ์เสร็จสิ้นแล้วค่อยทำ

**Comment by pchaow** [comment]
เตรียม ปฏิทินหรือตารางแจ้งเตือนขึ้นในหน้าแรก

**Comment by pchaow** [comment]
ทำเป็นตารางปฏิทินกับรายการ
