### ISSUE TITLE
[CattleFarmer] password 

### ISSUE THREAD

**Issue by ford19982541** [SEUP/CattleFarmer#49]
ไม่คอนเฟริมรหัสผ่าน  บันทึกได้ 
รหัสผ่านไม่ถูกปิด

**Comment by pchaow** [comment]
หน้าไหนนิ ตอนนี้ใครแก้ยัง

**Comment by pchaow** [comment]
![default](https://user-images.githubusercontent.com/5770600/45004641-86149680-b018-11e8-8b15-0fdb2e6fd463.png)
โอเค เจอแล้ว

**Comment by pchaow** [comment]
แก้แล้วเนาะ
