### ISSUE TITLE
[cattlefarmer && cattlenode] เเก้ความถูกต้องของผสมพันธุ์(เเม่พันธุ์)

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleFarmer#50]
สลับปุ่ม เเละย้อนกลับ
เมื่อกด ต่อไปเเล้วจะเป็นการ save 
ย้ายวันที่เป็นสัดมาเป็นสเต็ปสอง
เพิ่ม เช็คการกลับสัด 21 วัน หลักจากการผสมพันธุ์
เพิ่ม วันที่ต้องตรวจท้อง โดยสามารถตรวจสอบได้หลังจาก วัน /เดือน/ปี ที่ผสมไป 42-45 วัน เพื่อตรวจท้อง

**Comment by ford19982541** [comment]
เปลี่ยน "ต่อไป" เป็น "ถัดไป"

เอาสถานะสุดท้ายของการผสมพันธ์ุขึ้นมาโชว์

**Comment by ford19982541** [comment]
ใน 1 รอบการผสมมันเกิดอะไรขึ้นบ้าง "ได้ลูกมั้ย ? แท้งค์มั้ย?

**Comment by pchaow** [comment]
เสดยังนิ

**Comment by porrametict** [comment]
มีข้อผิดพลาดเพิ่มเติ่ม ต้องเเก้ โดยเช็ค ว่าการกด ต่อไป หรือไม่  เมื่อกดถัดไปต้อง บันทึกเเล้วกด โหลดข้อมูลลงมาให่ก่อน
